Task coordinator core logic [2]
microservices-course-itmo/designing_microservices_course pull request #13
Opened 2019-07-02 21:38 UTC by AfanasievYuriy

2019-07-03 18:00 UTC, andrsuh requested changes

2019-07-03 18:00 UTC, andrsuh commented on taskcoordinator/src/main/java/com/microservices/taskcoordinator/dto/outbound/OrderSubmissionDTO.java
>      int orderId;
modifiers

2019-07-03 18:00 UTC, andrsuh commented on taskcoordinator/src/main/java/com/microservices/taskcoordinator/service/impl/LaundryStateServiceImpl.java
> +            laundryStateEntity.setReservedTime(laundryStateEntity.getReservedTime() - order.getDuration());
reserved time should be changed in any case

2019-07-03 18:00 UTC, andrsuh commented on taskcoordinator/src/main/java/com/microservices/taskcoordinator/service/impl/LaundryStateServiceImpl.java
> +
2 blank lines

2019-07-03 18:00 UTC, andrsuh commented on taskcoordinator/src/main/java/com/microservices/taskcoordinator/service/impl/LaundryStateServiceImpl.java
> +        return laundryStateRepository.getLeastLoadedLaundry();
why you created separate method?

2019-07-03 18:00 UTC, andrsuh commented on taskcoordinator/src/main/java/com/microservices/taskcoordinator/service/impl/OrderServiceImpl.java
> +        OrderEntity orderEntityFound = orderRepository.findById(id)
what if id null? should it be a wrapper Integer?

2019-07-03 18:00 UTC, andrsuh commented on taskcoordinator/src/main/java/com/microservices/taskcoordinator/controllers/LaundryController.java
> -    public List<LaundryStateEntity> getLaundriesState() {
?

2019-07-03 18:00 UTC, andrsuh commented on taskcoordinator/src/main/java/com/microservices/taskcoordinator/dto/LaundryStateDTO.java
> +    private int laundryId;
seems like all the dtos should have the Object fields. Integer and Long

2019-07-03 18:00 UTC, andrsuh commented on taskcoordinator/src/main/java/com/microservices/taskcoordinator/entity/OrderDetailEntity.java
> +    private Integer id;
and vise versa. The entitis should use primitives where the field require not null

2019-07-03 18:00 UTC, andrsuh commented on taskcoordinator/src/main/java/com/microservices/taskcoordinator/dto/inbound/OrderSubmittedDTO.java
>  public class OrderSubmittedDTO {
Dto

2019-07-03 18:00 UTC, andrsuh commented on taskcoordinator/src/main/java/com/microservices/taskcoordinator/dto/inbound/OrderCoordinationDTO.java
> -public class OrderDTO {
Dto

2019-07-05 17:17 UTC, AfanasievYuriy commented on taskcoordinator/src/main/java/com/microservices/taskcoordinator/dto/outbound/OrderSubmissionDTO.java
>      int orderId;
fixed

2019-07-05 21:24 UTC, AfanasievYuriy commented on taskcoordinator/src/main/java/com/microservices/taskcoordinator/controllers/LaundryController.java
> -    public List<LaundryStateEntity> getLaundriesState() {
? this class is removed

2019-07-05 21:28 UTC, AfanasievYuriy commented on taskcoordinator/src/main/java/com/microservices/taskcoordinator/dto/LaundryStateDTO.java
> +    private int laundryId;
agree
fixed

2019-07-05 21:29 UTC, AfanasievYuriy commented on taskcoordinator/src/main/java/com/microservices/taskcoordinator/entity/OrderDetailEntity.java
> +    private Integer id;
disagree
https://stackoverflow.com/questions/11283709/always-use-primitive-object-wrappers-for-jpa-id-instead-of-primitive-type
https://stackoverflow.com/questions/3535791/primitive-or-wrapper-for-hibernate-primary-keys
https://stackoverflow.com/questions/3535791/primitive-or-wrapper-for-hibernate-primary-keys

2019-07-05 21:31 UTC, AfanasievYuriy commented on taskcoordinator/src/main/java/com/microservices/taskcoordinator/dto/inbound/OrderSubmittedDTO.java
>  public class OrderSubmittedDTO {
why?

2019-07-06 13:02 UTC, andrsuh approved these changes

2019-07-06 13:16 UTC, merged